
name: "NIST Duo Robot Arm ROS Demonsration"

robot: [fanuc_, motoman_] 

fanuc_base:
      trans:[0.0,-0.5,0.0]
      rot:[0.0,0.0,0.0,1.0]
motman_base:
      trans:[0.0,0.5,0.0]
      rot:[0.0,0.0,0.0,1.0]
fanuc_tool:
      trans:[0.017, 0.0,  0.140]
      rot:[0.0,0.0,0.0,1.0]
motman_tool:
      trans:[-0.017, 0.0, 0.140]
      rot:[0.0,0.0,0.0,1.0]
 
fanuc_bend: [180.0,0.0,0.0]

motoman_bend: [-180.0,0.0,0.0]


